// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie.Models;

namespace Movie.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    [Migration("20220130234634_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Movie.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CategoryID");

                    b.ToTable("NewResponses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            CategoryID = 1,
                            Director = "Robert Clouse",
                            Edited = "Yes",
                            LentTo = "Holywood",
                            Notes = "Bruce is the best!",
                            Rating = "R",
                            Title = "Enter the Dragon",
                            Year = 1973
                        },
                        new
                        {
                            ApplicationId = 2,
                            CategoryID = 1,
                            Director = "Bruce Lee",
                            Edited = "Yes",
                            LentTo = "Holywood",
                            Notes = "JDK",
                            Rating = "R",
                            Title = "The Way of the Dragon",
                            Year = 1970
                        },
                        new
                        {
                            ApplicationId = 3,
                            CategoryID = 1,
                            Director = "Daneil Creton",
                            Edited = "Yes",
                            LentTo = "Holywood",
                            Notes = "Simu Liu",
                            Rating = "PG-13",
                            Title = "ShangChi",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("Movie.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action/Adventure"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Horror/Suspense"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryName = "Miscellaneous"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryName = "Television"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryName = "VHS"
                        });
                });

            modelBuilder.Entity("Movie.Models.ApplicationResponse", b =>
                {
                    b.HasOne("Movie.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
